#!/bin/sh

sxhkd &
xrandr --output HDMI-0 --primary --mode 1920x1080 --rotate normal --output DP-0 --mode 1920x1080 --rotate normal --left-of HDMI-0
~/.config/polybar/launch.sh &

xsetroot -cursor_name left_ptr &

bspc monitor HDMI-0 -d 1 2 3 
bspc monitor DP-0 -d 4 5 6

bspc config border_width        1
bspc config window_gap          10

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# Setup rules to open certain applications

bspc rule -a Trello desktop=6 state=tiled follow=off focus=off
bspc rule -a discord desktop=4 state=tiled follow=off focus=off
bspc rule -a 'Minecraft* 1.16.5' desktop=1 state=fullscreen follow=off
bspc rule -a 'RLCraft' desktop=1 state=fullscreen follow=off
bspc rule -a 'TLauncher 2.841' desktop=1 state=tiled follow=off
bspc rule -a 'obs' state=floating follow=on
bspc rule -a 'Ubuntu Machine [Running] - Oracle VM VirtualBox' state=fullscreen
bspc rule -a 'MetaMask Notification' state=floating
#bspc rule -a Alacritty state=floating focus=on rectangle=750x400+3050+187
bspc rule -a Alacritty state=floating focus=on center=on rectangle=950x600+0+0
bspc rule -a 'vscodium' focus=on follow=on desktop=2 
bspc rule -a 'VSCodium' focus=on follow=on desktop=2 
bspc rule -a 'Android Emulator - Pixel_4_API_31:5554' state=floating
bspc rule -a 'Firefox Nightly' state=tiled

# Startup applications in designated workspaces
#[ -z "$(pidof trello)" ] && trello &
#[ -z "$(pidof Discord)" ] && discord &
