#!/bin/sh

sxhkd &
xrandr --output HDMI-0 --primary --mode 1920x1080 --rotate normal --output DP-0 --mode 1920x1080 --rotate normal --left-of HDMI-0
~/.config/polybar/launch.sh &

xsetroot -cursor_name left_ptr &

bspc monitor HDMI-0 -d 1 2 3
bspc monitor DP-0 -d 4 5

bspc config border_width        1
bspc config window_gap          0

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# Setup rules to open certain applications

bspc rule -a Trello desktop=6 state=tiled follow=off focus=off
bspc rule -a 'obs' state=floating follow=on
bspc rule -a 'MetaMask Notification' state=floating
bspc rule -a 'gl' state=floating center=on rectange=720x576+0+0
bspc rule -a 'mpv' state=floating center=on rectange=720x576+0+0
bspc rule -a 'Pcsx2' state=floating center=on follow=on

# Startup applications in designated workspaces
#[ -z "$(pidof trello)" ] && trello &
#[ -z "$(pidof Discord)" ] && discord &
