#! /bin/sh

sxhkd &
xrandr --output HDMI-0 --primary --mode 1920x1080 --rotate normal --output DP-0 --mode 1920x1080 --rotate normal --left-of HDMI-0
~/.config/polybar/launch.sh &

xsetroot -cursor_name left_ptr &

bspc monitor HDMI-0 -d 1 2 3 
bspc monitor DP-0 -d 4 5 6

bspc config border_width        2
bspc config window_gap          12

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Gimp desktop=^8 follow=on state=floating
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
